# Generated by Django 5.1.2 on 2025-02-11 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('refund_status', models.BooleanField(default=False)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.CharField(max_length=100)),
                ('card_id', models.CharField(max_length=100)),
                ('card_last_4', models.CharField(blank=True, max_length=4, null=True)),
                ('total_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True)),
                ('cart', models.JSONField(blank=True, default=dict)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100, null=True)),
                ('card_id', models.CharField(max_length=100, null=True)),
                ('last_4', models.CharField(blank=True, max_length=4, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
