# Generated by Django 5.1.2 on 2025-02-14 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_order_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='completed_status',
        ),
    ]
