# Generated by Django 5.1.2 on 2025-02-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_rename_status_order_completed_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='card_id',
            new_name='payment_id',
        ),
    ]
