# Generated by Django 5.1.2 on 2025-02-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='employee',
            field=models.BooleanField(default=False),
        ),
    ]
